name: Steve Light Portfolio
favicon: null
layout_spectrum: 0.8645
typography_spectrum: 0.06504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4285f4'
    - '#ea4335'
    - '#fbbc05'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
